builds:
  # You can have multiple builds defined as a yaml list
  -
    # Path to main.go file or main package.
    # Default is `.`.
    ldflags: -w -extldflags "-static" -X github.com/hashicorp/nomad/version.GitCommit={{ .Commit }}
   
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6

    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabi-gcc-5
